
 install.packages("Matrix")
library(Matrix, lib.loc = "C:/Program Files/R/R-4.2.0/library")
install.packages("Hmisc")
library(Hmisc)
install.packages("rlist")
library(rlist)
install.packages("yaml")
library(yaml)
install.packages("primes")
library(primes)
install.packages("bit64")
library(bit64)
install.packages("IRdisplay")
library(IRdisplay)
library(repr)
install.packages("vioplot")
library(vioplot)
install.packages("DT")
library(DT)
install.packages("ROCR")
library(ROCR)
install.packages("R.utils")
library(R.utils)
install.packages("Rcpp")
library(Rcpp)
install.packages("devtools")
library(devtools)
library(ggplot2)
install.packages("gganimate")
library(gganimate)
install.packages("transformr")
library(transformr)
install.packages("DiagrammeR")
library(DiagrammeR)
install.packages("data.table")
library(data.table)
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
install.packages("treeClust")
library(treeClust)
install.packages("ranger")
library(ranger)
install.packages("randomForest")
library(randomForest)
install.packages("xgboost")
library(xgboost)
install.packages("lightgbm")
library(lightgbm)
install.packages("DiceKriging")
library(DiceKriging)
install.packages("mlrMBO")
library(mlrMBO)



